const customLanguage = {
    tokenizer: {
        root: [

            [/\bSELECT\b/, 'keyword'],
            [/\bRENAME\b/, 'keyword'],
            [/\bFROM\b/, 'keyword'],
            [/\bWHERE\b/, 'keyword'],
            [/\bSEARCH\b/, 'keyword'],
            [/\bNULL\b/, 'keyword'],
            [/\bTRUE\b/, 'keyword'],
            [/\bFALSE\b/, 'keyword'],
            [/\bINT\b/, 'keyword'],
            [/\bVARCHAR\b/, 'keyword'],
            [/\bCREATE\b/, 'keyword'],
            [/\bTABLE\b/, 'keyword'],
            [/\bIF\b/, 'keyword'],
            [/\bEXISTS\b/, 'keyword'],
            [/\bPRIMARY KEY\b/, 'keyword'],
            [/\bFOREIGN KEY\b/, 'keyword'],
            [/\bREFERENCES\b/, 'keyword'],
            [/\bINSERT INTO\b/, 'keyword'],
            [/\bVALUES\b/, 'keyword'],
            [/\bUPDATE\b/, 'keyword'],
            [/\bSET\b/, 'keyword'],
            [/\bDELETE\b/, 'keyword'],
            [/\bDROP\b/, 'keyword'],
            [/\bDATABASE\b/, 'keyword'],
            [/\bUSE\b/, 'keyword'],
            [/\bNOT NULL\b/, 'keyword'],
            [/\bSHOW\b/, 'keyword'],
            [/\bT\b/, 'keyword'],
            [/\bL\b/, 'keyword'],
            [/\bF\b/, 'keyword'],
            [/\bCHAR\b/, 'keyword'],
            [/\bFLOAT\b/, 'keyword'],
            [/\bSTRING\b/, 'keyword'],
            [/\bBOOLEAN\b/, 'keyword'],
            [/\bTEXT\b/, 'keyword'],
            [/\bUNIQUE\b/, 'keyword'],
            [/[;,]/, 'delimiter'],
            [/#.*/, 'comment'],
            [/[+\-*/%=<>!?&|]/, 'operator'],
            [/[()\\[\]{}]/, 'delimiter.parenthesis'],
            [/\b\w+\b/, 'identifier'], // Tokenize identifiers (words)

            // Add your custom tokenization rules here
            // For example: [/\<[^\>]*\>/, 'tag'],
        ],
    },
};
export default customLanguage